[build]
target = "index.html"
public_url = "/"
dist = "../dist"
filehash = false

[[proxy]]
backend = "http://[::1]:8081/api/"

# gzip the assets
# -9 means best compression
# -k means don't delete the original file
[[hooks]]
stage = "post_build"
command = "bash"
command_arguments = [
    "-c",
    """gzip -9 -k $TRUNK_STAGING_DIR/{\
        index.html,\
        service-worker.js,\
        readtomyshoe-frontend.js,\
        readtomyshoe-frontend_bg.wasm\
    }"""
]
