use crate::tts::{GcpVoice, VoiceQuality, VoiceType};

use anyhow::{bail, Error as AnyError};
use whatlang::Lang;

/// Determines the language of the text and returns the ID of a voice matching the given sound
/// quality. If the voice type is available, the voice will match that too.
pub(crate) fn pick_tts_voice(
    text: &str,
    quality: VoiceQuality,
    ty: VoiceType,
) -> Result<&'static str, AnyError> {
    // Try to determine the language. If it's inconclusive, default to English
    let lang = whatlang::detect_lang(text).unwrap_or(Lang::Eng);
    tracing::info!("detected language {lang}");

    // Get the list of voices to choose from. If we chose high quality, then pick from Neural2,
    // then Wavenet, then Standard if need be.
    let list: Box<dyn Iterator<Item = &(Lang, GcpVoice)>> = match quality {
        VoiceQuality::Standard => Box::new(STANDARD_VOICES.iter()),
        VoiceQuality::High => Box::new(
            VOICE_OVERRIDES
                .iter()
                .chain(NEURAL2_VOICES.iter())
                .chain(WAVENET_VOICES.iter())
                .chain(STANDARD_VOICES.iter()),
        ),
    };

    // Collect all the voices in the desired language
    let lang_voices: Vec<GcpVoice> = list
        .filter_map(|v| if v.0 == lang { Some(v.1) } else { None })
        .collect();

    // If there are no supported voices in this langauge, error
    if lang_voices.is_empty() {
        bail!("Could not convert to speech. Language not supported");
    }

    // Try to find a voice of the given type. If that fails, return whatever the first voice was
    let voice = lang_voices
        .iter()
        .find(|v| v.ty == ty)
        .unwrap_or(&lang_voices[0]);

    // Return the voice ID
    Ok(voice.id)
}

// The following code was generated by gen_langs.py

const VOICE_OVERRIDES: &[(Lang, GcpVoice)] = &[
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-B",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-C",
            english_desc: "English (US)",
            ty: VoiceType::HighPitch,
        },
    ),
];

const STANDARD_VOICES: &[(Lang, GcpVoice)] = &[
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-FR-Standard-E",
            english_desc: "French (France)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-FR-Standard-D",
            english_desc: "French (France)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-FR-Standard-C",
            english_desc: "French (France)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-FR-Standard-B",
            english_desc: "French (France)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-FR-Standard-A",
            english_desc: "French (France)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-US-Standard-C",
            english_desc: "Spanish (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-US-Standard-B",
            english_desc: "Spanish (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-US-Standard-A",
            english_desc: "Spanish (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-BR-Standard-C",
            english_desc: "Portuguese (Brazil)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-BR-Standard-B",
            english_desc: "Portuguese (Brazil)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-BR-Standard-A",
            english_desc: "Portuguese (Brazil)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-NL-Standard-E",
            english_desc: "Dutch (Netherlands)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-NL-Standard-A",
            english_desc: "Dutch (Netherlands)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-NL-Standard-D",
            english_desc: "Dutch (Netherlands)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-NL-Standard-C",
            english_desc: "Dutch (Netherlands)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-NL-Standard-B",
            english_desc: "Dutch (Netherlands)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-CN-Standard-D",
            english_desc: "Mandarin Chinese (China)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-CN-Standard-A",
            english_desc: "Mandarin Chinese (China)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-CN-Standard-B",
            english_desc: "Mandarin Chinese (China)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-CN-Standard-C",
            english_desc: "Mandarin Chinese (China)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Standard-J",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Standard-I",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Standard-H",
            english_desc: "English (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Standard-G",
            english_desc: "English (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Standard-F",
            english_desc: "English (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Standard-E",
            english_desc: "English (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Standard-D",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Standard-C",
            english_desc: "English (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Standard-B",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Standard-A",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Standard-A",
            english_desc: "English (Australia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Standard-B",
            english_desc: "English (Australia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Standard-C",
            english_desc: "English (Australia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Standard-D",
            english_desc: "English (Australia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Standard-A",
            english_desc: "English (Australia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Standard-B",
            english_desc: "English (Australia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Standard-C",
            english_desc: "English (Australia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Standard-D",
            english_desc: "English (Australia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Standard-A",
            english_desc: "English (UK)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Standard-B",
            english_desc: "English (UK)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Standard-C",
            english_desc: "English (UK)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Standard-D",
            english_desc: "English (UK)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Standard-F",
            english_desc: "English (UK)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Cat,
        GcpVoice {
            id: "ca-ES-Standard-A",
            english_desc: "Catalan (Spain)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-ES-Standard-C",
            english_desc: "Spanish (Spain)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-ES-Standard-D",
            english_desc: "Spanish (Spain)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-ES-Standard-B",
            english_desc: "Spanish (Spain)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ara,
        GcpVoice {
            id: "ar-XA-Standard-A",
            english_desc: "Arabic",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ara,
        GcpVoice {
            id: "ar-XA-Standard-B",
            english_desc: "Arabic",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ara,
        GcpVoice {
            id: "ar-XA-Standard-C",
            english_desc: "Arabic",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ara,
        GcpVoice {
            id: "ar-XA-Standard-D",
            english_desc: "Arabic",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Rus,
        GcpVoice {
            id: "ru-RU-Standard-E",
            english_desc: "Russian (Russia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Rus,
        GcpVoice {
            id: "ru-RU-Standard-A",
            english_desc: "Russian (Russia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Rus,
        GcpVoice {
            id: "ru-RU-Standard-B",
            english_desc: "Russian (Russia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Rus,
        GcpVoice {
            id: "ru-RU-Standard-C",
            english_desc: "Russian (Russia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Rus,
        GcpVoice {
            id: "ru-RU-Standard-D",
            english_desc: "Russian (Russia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Jpn,
        GcpVoice {
            id: "ja-JP-Standard-A",
            english_desc: "Japanese (Japan)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Jpn,
        GcpVoice {
            id: "ja-JP-Standard-B",
            english_desc: "Japanese (Japan)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Jpn,
        GcpVoice {
            id: "ja-JP-Standard-C",
            english_desc: "Japanese (Japan)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Jpn,
        GcpVoice {
            id: "ja-JP-Standard-D",
            english_desc: "Japanese (Japan)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-TW-Standard-A",
            english_desc: "Mandarin Chinese (Taiwan, Province of China)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-TW-Standard-B",
            english_desc: "Mandarin Chinese (Taiwan, Province of China)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-TW-Standard-C",
            english_desc: "Mandarin Chinese (Taiwan, Province of China)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Kor,
        GcpVoice {
            id: "ko-KR-Standard-B",
            english_desc: "Korean (South Korea)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Kor,
        GcpVoice {
            id: "ko-KR-Standard-C",
            english_desc: "Korean (South Korea)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Kor,
        GcpVoice {
            id: "ko-KR-Standard-D",
            english_desc: "Korean (South Korea)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Kor,
        GcpVoice {
            id: "ko-KR-Standard-A",
            english_desc: "Korean (South Korea)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Vie,
        GcpVoice {
            id: "vi-VN-Standard-A",
            english_desc: "Vietnamese (Vietnam)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Vie,
        GcpVoice {
            id: "vi-VN-Standard-B",
            english_desc: "Vietnamese (Vietnam)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Vie,
        GcpVoice {
            id: "vi-VN-Standard-C",
            english_desc: "Vietnamese (Vietnam)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Vie,
        GcpVoice {
            id: "vi-VN-Standard-D",
            english_desc: "Vietnamese (Vietnam)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ind,
        GcpVoice {
            id: "id-ID-Standard-A",
            english_desc: "Indonesian (Indonesia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ind,
        GcpVoice {
            id: "id-ID-Standard-B",
            english_desc: "Indonesian (Indonesia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ind,
        GcpVoice {
            id: "id-ID-Standard-C",
            english_desc: "Indonesian (Indonesia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ind,
        GcpVoice {
            id: "id-ID-Standard-D",
            english_desc: "Indonesian (Indonesia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-BE-Standard-A",
            english_desc: "Dutch (Belgium)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-BE-Standard-B",
            english_desc: "Dutch (Belgium)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "yue-HK-Standard-A",
            english_desc: "Chinese (Hong Kong)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "yue-HK-Standard-B",
            english_desc: "Chinese (Hong Kong)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "yue-HK-Standard-C",
            english_desc: "Chinese (Hong Kong)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "yue-HK-Standard-D",
            english_desc: "Chinese (Hong Kong)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ces,
        GcpVoice {
            id: "cs-CZ-Standard-A",
            english_desc: "Czech (Czech Republic)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ell,
        GcpVoice {
            id: "el-GR-Standard-A",
            english_desc: "Greek (Greece)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Afr,
        GcpVoice {
            id: "af-ZA-Standard-A",
            english_desc: "Afrikaans (South Africa)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Bul,
        GcpVoice {
            id: "bg-BG-Standard-A",
            english_desc: "Bulgarian (Bulgaria)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Hun,
        GcpVoice {
            id: "hu-HU-Standard-A",
            english_desc: "Hungarian (Hungary)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Lav,
        GcpVoice {
            id: "lv-LV-Standard-A",
            english_desc: "Latvian (Latvia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ron,
        GcpVoice {
            id: "ro-RO-Standard-A",
            english_desc: "Romanian (Romania)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Srp,
        GcpVoice {
            id: "sr-rs-Standard-A",
            english_desc: "Serbian (Serbia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ukr,
        GcpVoice {
            id: "uk-UA-Standard-A",
            english_desc: "Ukranian (Ukraine)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Pol,
        GcpVoice {
            id: "pl-PL-Standard-A",
            english_desc: "Polish (Poland)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Pol,
        GcpVoice {
            id: "pl-PL-Standard-B",
            english_desc: "Polish (Poland)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Pol,
        GcpVoice {
            id: "pl-PL-Standard-C",
            english_desc: "Polish (Poland)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Pol,
        GcpVoice {
            id: "pl-PL-Standard-E",
            english_desc: "Polish (Poland)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Pol,
        GcpVoice {
            id: "pl-PL-Standard-D",
            english_desc: "Polish (Poland)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Tuk,
        GcpVoice {
            id: "tr-TR-Standard-B",
            english_desc: "Turkish (Turkey)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Tuk,
        GcpVoice {
            id: "tr-TR-Standard-C",
            english_desc: "Turkish (Turkey)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Tuk,
        GcpVoice {
            id: "tr-TR-Standard-D",
            english_desc: "Turkish (Turkey)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Tuk,
        GcpVoice {
            id: "tr-TR-Standard-A",
            english_desc: "Turkish (Turkey)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Tuk,
        GcpVoice {
            id: "tr-TR-Standard-E",
            english_desc: "Turkish (Turkey)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-IN-Standard-D",
            english_desc: "English (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-IN-Standard-A",
            english_desc: "English (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-IN-Standard-B",
            english_desc: "English (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-IN-Standard-C",
            english_desc: "English (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Tha,
        GcpVoice {
            id: "th-TH-Standard-A",
            english_desc: "Thai (Thailand)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ben,
        GcpVoice {
            id: "bn-IN-Standard-A",
            english_desc: "Bengali (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ben,
        GcpVoice {
            id: "bn-IN-Standard-B",
            english_desc: "Bengali (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Guj,
        GcpVoice {
            id: "gu-IN-Standard-A",
            english_desc: "Gujarati (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Guj,
        GcpVoice {
            id: "gu-IN-Standard-B",
            english_desc: "Gujarati (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Hin,
        GcpVoice {
            id: "hi-IN-Standard-D",
            english_desc: "Hindi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Hin,
        GcpVoice {
            id: "hi-IN-Standard-A",
            english_desc: "Hindi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Hin,
        GcpVoice {
            id: "hi-IN-Standard-B",
            english_desc: "Hindi (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Hin,
        GcpVoice {
            id: "hi-IN-Standard-C",
            english_desc: "Hindi (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Kan,
        GcpVoice {
            id: "kn-IN-Standard-A",
            english_desc: "Kannada (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Kan,
        GcpVoice {
            id: "kn-IN-Standard-B",
            english_desc: "Kannada (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Mal,
        GcpVoice {
            id: "ml-IN-Standard-A",
            english_desc: "Malayalam (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Mal,
        GcpVoice {
            id: "ml-IN-Standard-B",
            english_desc: "Malayalam (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Tam,
        GcpVoice {
            id: "ta-IN-Standard-C",
            english_desc: "Tamil (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Tam,
        GcpVoice {
            id: "ta-IN-Standard-D",
            english_desc: "Tamil (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Tam,
        GcpVoice {
            id: "ta-IN-Standard-A",
            english_desc: "Tamil (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Tam,
        GcpVoice {
            id: "ta-IN-Standard-B",
            english_desc: "Tamil (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Tel,
        GcpVoice {
            id: "te-IN-Standard-A",
            english_desc: "Telugu (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Tel,
        GcpVoice {
            id: "te-IN-Standard-B",
            english_desc: "Telugu (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Mar,
        GcpVoice {
            id: "mr-IN-Standard-A",
            english_desc: "Marathi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Mar,
        GcpVoice {
            id: "mr-IN-Standard-B",
            english_desc: "Marathi (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Mar,
        GcpVoice {
            id: "mr-IN-Standard-C",
            english_desc: "Marathi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Pan,
        GcpVoice {
            id: "pa-IN-Standard-A",
            english_desc: "Punjabi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Pan,
        GcpVoice {
            id: "pa-IN-Standard-B",
            english_desc: "Punjabi (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Pan,
        GcpVoice {
            id: "pa-IN-Standard-C",
            english_desc: "Punjabi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Pan,
        GcpVoice {
            id: "pa-IN-Standard-D",
            english_desc: "Punjabi (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Dan,
        GcpVoice {
            id: "da-DK-Standard-A",
            english_desc: "Danish (Denmark)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Dan,
        GcpVoice {
            id: "da-DK-Standard-C",
            english_desc: "Danish (Denmark)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Dan,
        GcpVoice {
            id: "da-DK-Standard-D",
            english_desc: "Danish (Denmark)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Dan,
        GcpVoice {
            id: "da-DK-Standard-E",
            english_desc: "Danish (Denmark)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-PT-Standard-A",
            english_desc: "Portuguese (Portugal)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-PT-Standard-B",
            english_desc: "Portuguese (Portugal)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-PT-Standard-C",
            english_desc: "Portuguese (Portugal)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-PT-Standard-D",
            english_desc: "Portuguese (Portugal)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Swe,
        GcpVoice {
            id: "sv-SE-Standard-B",
            english_desc: "Swedish (Sweden)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Swe,
        GcpVoice {
            id: "sv-SE-Standard-C",
            english_desc: "Swedish (Sweden)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Swe,
        GcpVoice {
            id: "sv-SE-Standard-D",
            english_desc: "Swedish (Sweden)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Swe,
        GcpVoice {
            id: "sv-SE-Standard-E",
            english_desc: "Swedish (Sweden)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Swe,
        GcpVoice {
            id: "sv-SE-Standard-A",
            english_desc: "Swedish (Sweden)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Standard-A",
            english_desc: "German (Germany)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Standard-B",
            english_desc: "German (Germany)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Standard-C",
            english_desc: "German (Germany)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Standard-D",
            english_desc: "German (Germany)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Standard-E",
            english_desc: "German (Germany)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Standard-F",
            english_desc: "German (Germany)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-CA-Standard-A",
            english_desc: "French (Canada)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-CA-Standard-B",
            english_desc: "French (Canada)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-CA-Standard-C",
            english_desc: "French (Canada)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-CA-Standard-D",
            english_desc: "French (Canada)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ita,
        GcpVoice {
            id: "it-IT-Standard-B",
            english_desc: "Italian (Italy)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ita,
        GcpVoice {
            id: "it-IT-Standard-C",
            english_desc: "Italian (Italy)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ita,
        GcpVoice {
            id: "it-IT-Standard-D",
            english_desc: "Italian (Italy)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Slk,
        GcpVoice {
            id: "sk-SK-Standard-A",
            english_desc: "Slovak (Slovakia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fin,
        GcpVoice {
            id: "fi-FI-Standard-A",
            english_desc: "Finnish (Finland)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ita,
        GcpVoice {
            id: "it-IT-Standard-A",
            english_desc: "Italian (Italy)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-ES-Standard-A",
            english_desc: "Spanish (Spain)",
            ty: VoiceType::HighPitch,
        },
    ),
];

const WAVENET_VOICES: &[(Lang, GcpVoice)] = &[
    (
        Lang::Por,
        GcpVoice {
            id: "pt-BR-Wavenet-C",
            english_desc: "Portuguese (Brazil)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-BR-Wavenet-B",
            english_desc: "Portuguese (Brazil)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-BR-Wavenet-A",
            english_desc: "Portuguese (Brazil)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-NL-Wavenet-E",
            english_desc: "Dutch (Netherlands)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-NL-Wavenet-A",
            english_desc: "Dutch (Netherlands)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-NL-Wavenet-D",
            english_desc: "Dutch (Netherlands)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-NL-Wavenet-C",
            english_desc: "Dutch (Netherlands)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-NL-Wavenet-B",
            english_desc: "Dutch (Netherlands)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-CN-Wavenet-D",
            english_desc: "Mandarin Chinese (China)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-CN-Wavenet-C",
            english_desc: "Mandarin Chinese (China)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-CN-Wavenet-B",
            english_desc: "Mandarin Chinese (China)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-CN-Wavenet-A",
            english_desc: "Mandarin Chinese (China)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-FR-Wavenet-D",
            english_desc: "French (France)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-FR-Wavenet-C",
            english_desc: "French (France)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-FR-Wavenet-B",
            english_desc: "French (France)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-FR-Wavenet-A",
            english_desc: "French (France)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-FR-Wavenet-E",
            english_desc: "French (France)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-US-Wavenet-C",
            english_desc: "Spanish (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-US-Wavenet-B",
            english_desc: "Spanish (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-US-Wavenet-A",
            english_desc: "Spanish (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-F",
            english_desc: "English (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-E",
            english_desc: "English (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-D",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-C",
            english_desc: "English (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-B",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-A",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-J",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-I",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-H",
            english_desc: "English (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Wavenet-G",
            english_desc: "English (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ara,
        GcpVoice {
            id: "ar-XA-Wavenet-A",
            english_desc: "Arabic",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ara,
        GcpVoice {
            id: "ar-XA-Wavenet-B",
            english_desc: "Arabic",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ara,
        GcpVoice {
            id: "ar-XA-Wavenet-C",
            english_desc: "Arabic",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ara,
        GcpVoice {
            id: "ar-XA-Wavenet-D",
            english_desc: "Arabic",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ben,
        GcpVoice {
            id: "bn-IN-Wavenet-A",
            english_desc: "Bengali (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ben,
        GcpVoice {
            id: "bn-IN-Wavenet-B",
            english_desc: "Bengali (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Wavenet-A",
            english_desc: "English (UK)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Wavenet-B",
            english_desc: "English (UK)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Wavenet-C",
            english_desc: "English (UK)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Wavenet-D",
            english_desc: "English (UK)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Wavenet-F",
            english_desc: "English (UK)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-CA-Wavenet-A",
            english_desc: "French (Canada)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-CA-Wavenet-B",
            english_desc: "French (Canada)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-CA-Wavenet-C",
            english_desc: "French (Canada)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Fra,
        GcpVoice {
            id: "fr-CA-Wavenet-D",
            english_desc: "French (Canada)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-ES-Wavenet-C",
            english_desc: "Spanish (Spain)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-ES-Wavenet-D",
            english_desc: "Spanish (Spain)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-ES-Wavenet-B",
            english_desc: "Spanish (Spain)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Fin,
        GcpVoice {
            id: "fi-FI-Wavenet-A",
            english_desc: "Finnish (Finland)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Guj,
        GcpVoice {
            id: "gu-IN-Wavenet-A",
            english_desc: "Gujarati (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Guj,
        GcpVoice {
            id: "gu-IN-Wavenet-B",
            english_desc: "Gujarati (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Jpn,
        GcpVoice {
            id: "ja-JP-Wavenet-B",
            english_desc: "Japanese (Japan)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Jpn,
        GcpVoice {
            id: "ja-JP-Wavenet-C",
            english_desc: "Japanese (Japan)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Jpn,
        GcpVoice {
            id: "ja-JP-Wavenet-D",
            english_desc: "Japanese (Japan)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Jpn,
        GcpVoice {
            id: "ja-JP-Wavenet-A",
            english_desc: "Japanese (Japan)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Kan,
        GcpVoice {
            id: "kn-IN-Wavenet-A",
            english_desc: "Kannada (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Kan,
        GcpVoice {
            id: "kn-IN-Wavenet-B",
            english_desc: "Kannada (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Mal,
        GcpVoice {
            id: "ml-IN-Wavenet-A",
            english_desc: "Malayalam (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Mal,
        GcpVoice {
            id: "ml-IN-Wavenet-B",
            english_desc: "Malayalam (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Mar,
        GcpVoice {
            id: "mr-IN-Wavenet-A",
            english_desc: "Marathi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Mar,
        GcpVoice {
            id: "mr-IN-Wavenet-B",
            english_desc: "Marathi (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Mar,
        GcpVoice {
            id: "mr-IN-Wavenet-C",
            english_desc: "Marathi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Swe,
        GcpVoice {
            id: "sv-SE-Wavenet-A",
            english_desc: "Swedish (Sweden)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Swe,
        GcpVoice {
            id: "sv-SE-Wavenet-B",
            english_desc: "Swedish (Sweden)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Swe,
        GcpVoice {
            id: "sv-SE-Wavenet-C",
            english_desc: "Swedish (Sweden)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Swe,
        GcpVoice {
            id: "sv-SE-Wavenet-D",
            english_desc: "Swedish (Sweden)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Swe,
        GcpVoice {
            id: "sv-SE-Wavenet-E",
            english_desc: "Swedish (Sweden)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Tam,
        GcpVoice {
            id: "ta-IN-Wavenet-A",
            english_desc: "Tamil (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Tam,
        GcpVoice {
            id: "ta-IN-Wavenet-B",
            english_desc: "Tamil (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Tam,
        GcpVoice {
            id: "ta-IN-Wavenet-C",
            english_desc: "Tamil (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Tam,
        GcpVoice {
            id: "ta-IN-Wavenet-D",
            english_desc: "Tamil (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Tuk,
        GcpVoice {
            id: "tr-TR-Wavenet-B",
            english_desc: "Turkish (Turkey)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Tuk,
        GcpVoice {
            id: "tr-TR-Wavenet-C",
            english_desc: "Turkish (Turkey)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Tuk,
        GcpVoice {
            id: "tr-TR-Wavenet-D",
            english_desc: "Turkish (Turkey)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Tuk,
        GcpVoice {
            id: "tr-TR-Wavenet-E",
            english_desc: "Turkish (Turkey)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Tuk,
        GcpVoice {
            id: "tr-TR-Wavenet-A",
            english_desc: "Turkish (Turkey)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Pan,
        GcpVoice {
            id: "pa-IN-Wavenet-A",
            english_desc: "Punjabi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Pan,
        GcpVoice {
            id: "pa-IN-Wavenet-B",
            english_desc: "Punjabi (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Pan,
        GcpVoice {
            id: "pa-IN-Wavenet-C",
            english_desc: "Punjabi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Pan,
        GcpVoice {
            id: "pa-IN-Wavenet-D",
            english_desc: "Punjabi (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ces,
        GcpVoice {
            id: "cs-CZ-Wavenet-A",
            english_desc: "Czech (Czech Republic)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Wavenet-F",
            english_desc: "German (Germany)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Wavenet-A",
            english_desc: "German (Germany)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Wavenet-B",
            english_desc: "German (Germany)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Wavenet-C",
            english_desc: "German (Germany)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Wavenet-D",
            english_desc: "German (Germany)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Deu,
        GcpVoice {
            id: "de-DE-Wavenet-E",
            english_desc: "German (Germany)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Wavenet-A",
            english_desc: "English (Australia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Wavenet-B",
            english_desc: "English (Australia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Wavenet-C",
            english_desc: "English (Australia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Wavenet-D",
            english_desc: "English (Australia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-IN-Wavenet-D",
            english_desc: "English (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-IN-Wavenet-A",
            english_desc: "English (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-IN-Wavenet-B",
            english_desc: "English (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-IN-Wavenet-C",
            english_desc: "English (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Hin,
        GcpVoice {
            id: "hi-IN-Wavenet-D",
            english_desc: "Hindi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Hin,
        GcpVoice {
            id: "hi-IN-Wavenet-A",
            english_desc: "Hindi (India)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Hin,
        GcpVoice {
            id: "hi-IN-Wavenet-B",
            english_desc: "Hindi (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Hin,
        GcpVoice {
            id: "hi-IN-Wavenet-C",
            english_desc: "Hindi (India)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ind,
        GcpVoice {
            id: "id-ID-Wavenet-D",
            english_desc: "Indonesian (Indonesia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ind,
        GcpVoice {
            id: "id-ID-Wavenet-A",
            english_desc: "Indonesian (Indonesia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ind,
        GcpVoice {
            id: "id-ID-Wavenet-B",
            english_desc: "Indonesian (Indonesia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ind,
        GcpVoice {
            id: "id-ID-Wavenet-C",
            english_desc: "Indonesian (Indonesia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ita,
        GcpVoice {
            id: "it-IT-Wavenet-A",
            english_desc: "Italian (Italy)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ita,
        GcpVoice {
            id: "it-IT-Wavenet-B",
            english_desc: "Italian (Italy)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ita,
        GcpVoice {
            id: "it-IT-Wavenet-C",
            english_desc: "Italian (Italy)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ita,
        GcpVoice {
            id: "it-IT-Wavenet-D",
            english_desc: "Italian (Italy)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Kor,
        GcpVoice {
            id: "ko-KR-Wavenet-A",
            english_desc: "Korean (South Korea)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Kor,
        GcpVoice {
            id: "ko-KR-Wavenet-B",
            english_desc: "Korean (South Korea)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Kor,
        GcpVoice {
            id: "ko-KR-Wavenet-C",
            english_desc: "Korean (South Korea)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Kor,
        GcpVoice {
            id: "ko-KR-Wavenet-D",
            english_desc: "Korean (South Korea)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Rus,
        GcpVoice {
            id: "ru-RU-Wavenet-E",
            english_desc: "Russian (Russia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Rus,
        GcpVoice {
            id: "ru-RU-Wavenet-A",
            english_desc: "Russian (Russia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Rus,
        GcpVoice {
            id: "ru-RU-Wavenet-B",
            english_desc: "Russian (Russia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Rus,
        GcpVoice {
            id: "ru-RU-Wavenet-C",
            english_desc: "Russian (Russia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Rus,
        GcpVoice {
            id: "ru-RU-Wavenet-D",
            english_desc: "Russian (Russia)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Ukr,
        GcpVoice {
            id: "uk-UA-Wavenet-A",
            english_desc: "Ukranian (Ukraine)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-TW-Wavenet-A",
            english_desc: "Mandarin Chinese (Taiwan, Province of China)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-TW-Wavenet-B",
            english_desc: "Mandarin Chinese (Taiwan, Province of China)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Cmn,
        GcpVoice {
            id: "cmn-TW-Wavenet-C",
            english_desc: "Mandarin Chinese (Taiwan, Province of China)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Dan,
        GcpVoice {
            id: "da-DK-Wavenet-C",
            english_desc: "Danish (Denmark)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Dan,
        GcpVoice {
            id: "da-DK-Wavenet-D",
            english_desc: "Danish (Denmark)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Dan,
        GcpVoice {
            id: "da-DK-Wavenet-E",
            english_desc: "Danish (Denmark)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Dan,
        GcpVoice {
            id: "da-DK-Wavenet-A",
            english_desc: "Danish (Denmark)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ell,
        GcpVoice {
            id: "el-GR-Wavenet-A",
            english_desc: "Greek (Greece)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Hun,
        GcpVoice {
            id: "hu-HU-Wavenet-A",
            english_desc: "Hungarian (Hungary)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-BE-Wavenet-A",
            english_desc: "Dutch (Belgium)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Nld,
        GcpVoice {
            id: "nl-BE-Wavenet-B",
            english_desc: "Dutch (Belgium)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-PT-Wavenet-A",
            english_desc: "Portuguese (Portugal)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-PT-Wavenet-B",
            english_desc: "Portuguese (Portugal)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-PT-Wavenet-C",
            english_desc: "Portuguese (Portugal)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Por,
        GcpVoice {
            id: "pt-PT-Wavenet-D",
            english_desc: "Portuguese (Portugal)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Slk,
        GcpVoice {
            id: "sk-SK-Wavenet-A",
            english_desc: "Slovak (Slovakia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Vie,
        GcpVoice {
            id: "vi-VN-Wavenet-A",
            english_desc: "Vietnamese (Vietnam)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Vie,
        GcpVoice {
            id: "vi-VN-Wavenet-B",
            english_desc: "Vietnamese (Vietnam)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Vie,
        GcpVoice {
            id: "vi-VN-Wavenet-C",
            english_desc: "Vietnamese (Vietnam)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Vie,
        GcpVoice {
            id: "vi-VN-Wavenet-D",
            english_desc: "Vietnamese (Vietnam)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Pol,
        GcpVoice {
            id: "pl-PL-Wavenet-A",
            english_desc: "Polish (Poland)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Pol,
        GcpVoice {
            id: "pl-PL-Wavenet-B",
            english_desc: "Polish (Poland)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Pol,
        GcpVoice {
            id: "pl-PL-Wavenet-C",
            english_desc: "Polish (Poland)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Pol,
        GcpVoice {
            id: "pl-PL-Wavenet-E",
            english_desc: "Polish (Poland)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Pol,
        GcpVoice {
            id: "pl-PL-Wavenet-D",
            english_desc: "Polish (Poland)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Ron,
        GcpVoice {
            id: "ro-RO-Wavenet-A",
            english_desc: "Romanian (Romania)",
            ty: VoiceType::HighPitch,
        },
    ),
];

const NEURAL2_VOICES: &[(Lang, GcpVoice)] = &[
    (
        Lang::Eng,
        GcpVoice {
            id: "en-US-Neural2-A",
            english_desc: "English (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-US-Neural2-C",
            english_desc: "Spanish (US)",
            ty: VoiceType::LowPitch,
        },
    ),
    (
        Lang::Spa,
        GcpVoice {
            id: "es-US-Neural2-A",
            english_desc: "Spanish (US)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Neural2-A",
            english_desc: "English (UK)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-GB-Neural2-C",
            english_desc: "English (UK)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Neural2-A",
            english_desc: "English (Australia)",
            ty: VoiceType::HighPitch,
        },
    ),
    (
        Lang::Eng,
        GcpVoice {
            id: "en-AU-Neural2-C",
            english_desc: "English (Australia)",
            ty: VoiceType::HighPitch,
        },
    ),
];
